version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${DB_PORT}
      MYSQL_UNIX_PORT: ${DB_PORT}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"